### ISSUE TITLE
Linker error building on OSX 10.9.5

### ISSUE THREAD

**Issue by chemecse** [networkprotocol/libyojimbo#1]
Encountered the following error while running `premake5 gmake && make all`:
```
Building configurations...
Running action 'gmake'...
Generated Makefile...
Generated test.make...
Generated connect.make...
Generated info.make...
Generated yojimbo.make...
Generated client.make...
Generated server.make...
Generated secure_server.make...
Generated client_server.make...
Generated soak.make...
Generated profile.make...
Generated simple_messages.make...
Done (43ms).
==== Building yojimbo (debug_x64) ====
Creating bin
Creating obj/x64/Debug/yojimbo
yojimbo.cpp
yojimbo_address.cpp
yojimbo_channel.cpp
yojimbo_client_server.cpp
yojimbo_common.cpp
yojimbo_connection.cpp
yojimbo_encryption.cpp
yojimbo_matcher.cpp
yojimbo_network.cpp
yojimbo_packet.cpp
yojimbo_packet_processor.cpp
yojimbo_platform.cpp
yojimbo_simulator.cpp
yojimbo_sockets.cpp
yojimbo_transport.cpp
Linking yojimbo
==== Building test (debug_x64) ====
Creating obj/x64/Debug/test
test.cpp
Linking test
ld: warning: directory not found for option '-L/usr/lib64'
ld: unknown option: --start-group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/test] Error 1
make: *** [test] Error 2
```

From what I can tell, there isn't a `lib64` and clang targeting Darwin doesn't support `--start-group`/`--end-group` on OSX.

`premake5 --version` outputs: `premake5 (Premake Build Script Generator) 5.0.0-alpha9`
`make -v` outputs: `GNU Make 3.81`
`clang -v` outputs:
```
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

**Comment by chemecse** [comment]
`make test && ./bin/test` works correctly after I remove `-L/usr/lib64`, `--start-group`, and `--end-group` manually from `test.make`.

**Comment by gafferongames** [comment]
Thank you very much for this report. Are you on a 32bit system or a 64bit MacOS system?

**Comment by gafferongames** [comment]
Thanks for this report! 

I have had in 200 beta testers, one report of this exact error before. It is not just your machine. There is something going on.

I suspect this is a bug in premake5 because it is generating the makefile that you are having problems with. 

I am successfully building on:

OSX 10.11.5
premake5 (Premake Build Script Generator) 5.0.0-alpha8
GNU Make 3.81

Clang:

    clang version 3.8.0 (tags/checker/checker-278)
    Target: x86_64-apple-darwin15.5.0
    Thread model: posix
    InstalledDir: /Tools/clang-check/bin

**Comment by gafferongames** [comment]
Sorry, I think I have two versions of clang on my system: 

llvm -v reports:

    Apple LLVM version 7.3.0 (clang-703.0.31)
    Target: x86_64-apple-darwin15.5.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by chemecse** [comment]
I am on a 64-bit machine, agreed that it's a premake5 issue. This might be the kick I need to finally upgrade my OSX version... haha

**Comment by gafferongames** [comment]
I think so, but until then I will add this workaround to the BUILDING.md so people know what to do if they get this issue on an older MacOSX

**Comment by gafferongames** [comment]
Can you take this particular bug to https://github.com/premake/premake-core/issues, and perhaps see if it still occurs with the latest premake5 source?

I will update BUILDING.md with this workaround, and close this issue out.

Thanks!

**Comment by chemecse** [comment]
👍

**Comment by gafferongames** [comment]
Updated BUILDING.md with your workaround and a link to the premake github to hassle them :)

https://github.com/networkprotocol/libyojimbo/blob/master/BUILDING.md

**Comment by chemecse** [comment]
Here's the issue I created on the premake-core project, thanks for posting the workaround.
https://github.com/premake/premake-core/issues/548

**Comment by chemecse** [comment]
Update: the current master branch of `premake-core` does not generate a Makefile with  `--start-group` or `--end-group`, but still attempts to link with `-L/usr/lib64`.
For reference, this premake version is `premake5 (Premake Build Script Generator) 5.0.0-dev`.

**Comment by gafferongames** [comment]
Good to know. Hopefully they fix it soon.
