### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by bluebear94** [networkprotocol/libyojimbo#18]
The repository already has a few pieces of sample code, but seems to lack any other kind of documentation.

**Comment by gafferongames** [comment]
Good call. What sort of documentation would you like to see?

**Comment by gafferongames** [comment]
I will work on some documentation shortly. Closing this issue out until then.

**Comment by gafferongames** [comment]
I am I think about 2/3rds of the way through writing doxygen documentation for the project. To check it out, download the latest source and run "premake5 docs". 

cheers

- Glenn

**Comment by gafferongames** [comment]
Documentation has been completed.
