### ISSUE TITLE
windows.h SendMessage conflict

### ISSUE THREAD

**Issue by Velro** [networkprotocol/libyojimbo#19]
When Windows.h is included, any function named SendMessage gets macro expanded to SendMessageW or SendMessageA. 

I'm not sure if this is something you want to handle in the library or let the user deal with, just seems like something other people would hit and be confused about like me. 

I personally worked around this by using a MSVC pragma and renaming the function in my inherited Client.

```cpp
#pragma push_macro("SendMessage")
#undef SendMessage

void GameClient::SendGameMessage( GameMessage* Message )
{
    Assert( IsConnected() );
    Assert( m_messageFactory );
    Assert( m_connection );
    m_connection->SendMessage( Message );
}
#pragma pop_macro("SendMessage")
```

**Comment by gafferongames** [comment]
Ugh. Windows...

**Comment by gafferongames** [comment]
Yeah this sucks. I fixed it in the development branch by renaming all the message related functions to "CanSendMsg", "SendMsg" etc.

**Comment by gafferongames** [comment]
Fixed in development branch: https://github.com/networkprotocol/libyojimbo/commit/9b665ac2ff068bf3a847b7fd638e3f3fe679c87d
