### ISSUE TITLE
Possible to support openid connect authentication flow?

### ISSUE THREAD

**Issue by fire** [networkprotocol/libyojimbo#20]
Not sure how hard it is to support json web tokens (JWT) as a token authentication method to https servers. 

For example being able to use Google accounts / Facebook accounts / Github accounts / Run your own openidc server with keycloak accounts.

**Comment by gafferongames** [comment]
I think that stuff is a great idea, eventually the backend matcher should be able to be extended (or integrated with your own matcher) that provides this auth, and then it creates the connect token to pass to the yojimbo dedicated server on connect. But I don't plan to add this functionality directly to yojimbo.

**Comment by fire** [comment]
Can you leave details hints where this functionality can be added? It would be helpful.

I'm tempted to write my own backend just for fun.

**Comment by gafferongames** [comment]
Take a look at matcher.go, that's where it would all be done.

**Comment by gafferongames** [comment]
ps. You don't have to base your backend on matcher.go, but it would act as an example of how to create a connect token and how to respond to a matcher request, and you would port that code into whatever backend language you decide to use.



cheers

**Comment by gafferongames** [comment]
ps. For what it's worth, the yojimbo connect tokens are pretty similar to JWT in concept.
