### ISSUE TITLE
Puzzled about the server AdvanceTime, why initialize to 100.0

### ISSUE THREAD

**Issue by adzhang** [networkprotocol/libyojimbo#22]
In addition, I suggest changing platform_sleep for a varied time like this.

`const int logicFrame = 60;
    double accumilatedTime = 0;
    double deltaTime = platform_time();
    double logicFrameLength = 1.0/logicFrame;

    while( !quit )
    {
        double now = platform_time();
        accumilatedTime += now-deltaTime;
        deltaTime = now;

        while( accumilatedTime > logicFrameLength )
        {
            server.SendPackets();

            serverTransport.WritePackets();

            serverTransport.ReadPackets();

            server.ReceivePackets();

            server.CheckForTimeOut();

            time += logicFrameLength;

            server.AdvanceTime( time );

            serverTransport.AdvanceTime( time );

            accumilatedTime -= logicFrameLength;
        }

        platform_sleep( logicFrameLength-accumilatedTime );
    }`

**Comment by gafferongames** [comment]
There was a class of bugs that only showed up when time was further away from 0.0 than timeout. These bugs were masked by tests all starting time at 0.0. After I fixed these bugs, I updated all tests to start time at 100.0 so if these bugs ever came back, the tests would catch them.
