### ISSUE TITLE
Sequence Buffer Question

### ISSUE THREAD

**Issue by RandyGaul** [networkprotocol/libyojimbo#29]
Just a quick question. I was reviewing this line here: https://github.com/networkprotocol/libyojimbo/blob/master/yojimbo_sequence_buffer.h#L71

        T * Insert( uint16_t sequence )
        {
            if ( sequence_greater_than( sequence + 1, m_sequence ) )
            {
                RemoveEntries( m_sequence, sequence );

                m_sequence = sequence + 1;
            }
           
            // THIS LINE HERE
            else if ( sequence_less_than( sequence, m_sequence - m_size ) )
            {
                return NULL;
            }

            const int index = sequence % m_size;

            m_entry_sequence[index] = sequence;

            return &m_entries[index];
        }

I've been trying to understand what this is checking exactly. My best guess it to catch old packets that would possibly have wrapped around the buffer size, but have yet to wrap around a full uint16_t. Could you possibly shed a little light here? Thank you!

**Comment by gafferongames** [comment]
It's to catch old packets that DON'T fit in the sequence buffer, eg. if the most recente packet sequence number is 1024 and the sequence buffer size is 512, then packets with sequence numbers 511 and older would be rejected by the else if.

cheers

**Comment by maestro92** [comment]
Just aother quick question regarding the line:
if ( sequence_greater_than( sequence + 1, m_sequence ) )

why do you need the +1 there?
