### ISSUE TITLE
Messages, Packets, Frames and Time

### ISSUE THREAD

**Issue by mikesun** [networkprotocol/libyojimbo#31]
I'm somewhat confused about how messages are carried on packets with regard to the frame concept and time.

Let's say I setup an unreliable, unordered channel between client and server.  I want my client to send one message every 20 ms to the serve -- the message size is smaller than the max packet size. After the connection and channel is established between client and server, I would think only one packet would be need to be sent to carry that message.

Based on the code the function `PumpClientServerUpdate()` in `tests/test.cpp`, I made this test:

Example client code:
```
// After connection established
...
client->SendMsg(message);
client->SendPackets();
transport->WritePackets();
...
```

Example server code:
```
// After connection established
...
while (true) {
    ...
    transport.ReadPackets();
    server.ReceivePackets();
    ...
}
```

In my tests, the message is not received by the server when only one packet is sent from the client. In fact, it requires ~300 packets to be sent from the client before the server is able to receive the message.

What's the correct usage of `SendMessage()`  vis-a-vis `SendPackets()` for a game frame update? 
It seems that `SendMessage()` queues up the message and `SendPackets()` adds to the transport's packet queue a *single* connection packet with a *single* message from the message queue. But in my tests, it seems fore every `SendMessage()` called, I have to call `SendPackets()` ~300 times for the message to be received.

 Also if I want to send multiple messages every frame (calling `SendMessage()` multiple times), it seems that a single call to `SendPackets()` every frame will only send to the transport a single packet with a single message during that frame.

Practically speaking, If I want to send multiple messages every game frame update, do I have to call `SendPackets()` at a higher frequency than the frame update frequency?

**Comment by gafferongames** [comment]
Packets from client -> server are sent at the rate that you call Client::SendPackets.

Packets from server -> client are sent at the rate that you call Server::SendPackets.

If you would like to send packets less frequently, like 20HZ, setup a loop that runs a frame, sleeps until the next 1/20th of a second interval, then wakes up, rinse and repeat. 

cheers

**Comment by gafferongames** [comment]
ps. Why is this:

libyojimbo is designed around protocols that continuously exchange packets in both directions, like FPS games. Therefore there are no ack packets, acks from server -> client piggy back on regular packets sent from server -> client and vice-versa.

This is in contrast to many other protocols, which only try to send packets when you have data to send, and have separate ack packets. Yojimbo has at its core the assumption that you have a steady state "carrier wave" of packets in both directions. It makes a lot of things more efficient, and works great in the context of games that have some unreliable steady state data that makes up the bulk of their protocol that needs to be sent at some rate anyway, like inputs from client -> server @ 60HZ, and snapshots of world state from server -> client @ 20HZ from server to client.

In this context, the bulk of the packets are normally this unreliable data, and the messages and acks are just taking a ride on this carrier wave. Much more cheaply, than if they were sent in separate packets, or some packet aggregation approach was performed for reliable packets v.s unreliable packets into some wire packet aggregate.

cheers

- Glenn

**Comment by gafferongames** [comment]
ps. Are you calling AdvanceTime properly on all objects in your loop? Please post the entire main loop you are using for libyojimbo on client and server so I can see what's going on.

**Comment by gafferongames** [comment]
> In my tests, the message is not received by the server when only one packet is sent from the client. In 
> fact, it requires ~300 packets to be sent from the client before the server is able to receive the message.

This is not expected behavior. Something is wrong.

**Comment by gafferongames** [comment]
> Practically speaking, If I want to send multiple messages every game frame update, do I have to call 
> SendPackets() at a higher frequency than the frame update frequency?

It depends on the size of the message and the channel budget. Check out the latest libyojimbo source which has doxygen comments in it, and build docs with "premake5 docs". Inside these docs, look up "ChannelConfig", "MessageConfig" and "ClientServerConfig" classes.

You may need to make adjustments to these to configure the packet budgets and channels to what you want. The behavior also depends on whether this is a reliable-ordered channel, or an unreliable-unordered channel, and how large the block of data you are sending, and whether it is a block message or a regular message with serialize functions.

So please let me know these things.

cheers 

- Glenn

**Comment by gafferongames** [comment]
Looking at your code above, I'm guessing you are only sending packets in the direction from client to server. Even if you want to send messages only from client -> server, you still need to send packets from client -> server and server -> client at a steady rate. If you are not doing this, then that the source of your issues.

**Comment by RandyGaul** [comment]
It looks like this topic keeps coming up in issues. Perhaps it should be a major point in docs somewhere? That is, to keep a steady flow of packets so acks and messages get through?

**Comment by gafferongames** [comment]
Yes, I plan to write usage docs, but I have to find the time to write these. Until then, covering this in issues that people can search through is the best I can do. I'm also using these issues to discover pain points and what people NEED to have documented...

cheers

**Comment by mikesun** [comment]
> Looking at your code above, I'm guessing you are only sending packets in the direction from client to server after you establish connection. However, even if you only want to send messages from client -> server, you still need to send packets from both client -> server and server -> client at a steady rate.

> If you are not doing this, then this is the cause of your issue.

I am sending packets from the server to the client at steady rate; I'm just not sending messages from the server to the client.

Using a unreliable, unordered channel with a regular  message that is smaller than the max packet size.

Will provide sample main functions soon.

**Comment by gafferongames** [comment]
OK sounds good. I'll check out your sample and see what's going on

**Comment by gafferongames** [comment]
To answer this question:

> Practically speaking, If I want to send multiple messages every game frame update, do I have to call 
> SendPackets() at a higher frequency than the frame update frequency?

No you should not need to do this.

**Comment by mikesun** [comment]
Okay, so here's some sample test client and server code based off my actual code. It uses the client/server and message types defined in `shared.h`.

Client
```
#define CLIENT 1
#define LOGGING 1

#include "shared.h" 
#include <signal.h>

static volatile int quit = 0;

void interrupt_handler(int)
{
    quit = 1;
}

int ClientMain()
{
    double time = 0.0;
    const double deltaTime = 0.02;
    uint64_t clientId = 777;

    signal(SIGINT, interrupt_handler);

    // Initialize network transport
    NetworkTransport transport(GetDefaultAllocator(), Address("0.0.0.0"), 
        ProtocolId, time);
    if (transport.GetError() != SOCKET_ERROR_NONE) {
        return 1;
    }
    transport.SetFlags(TRANSPORT_FLAG_INSECURE_MODE);

    // Configure connection properties 
    ClientServerConfig config;
    config.connectionConfig.maxPacketSize = 1500;
    config.connectionConfig.numChannels = 1;
    config.connectionConfig.channel[0].type = CHANNEL_TYPE_UNRELIABLE_UNORDERED;

    // Initialize client
    GameClient client(GetDefaultAllocator(), transport, config, time);

    // Connect to server
    Address serverAddress("127.0.0.1", ServerPort);
    client.InsecureConnect(clientId, serverAddress);
    while (!quit) {
        client.SendPackets();
        transport.WritePackets();
        transport.ReadPackets();
        client.ReceivePackets();
        client.CheckForTimeOut();

        time += deltaTime;
        client.AdvanceTime(time);
        transport.AdvanceTime(time);

        if (client.ConnectionFailed()) {
            return 1;
        }

        if (!client.IsConnecting() && client.IsConnected()) {
            break;
        }

        platform_sleep(deltaTime);
    }


    // Send message (i.e. enqueue)
    TestMessage *message = (TestMessage *) client.CreateMsg(TEST_MESSAGE);
    message->sequence = 0;
    client.SendMsg(message);

    // Send packets
    // MUST SEND AT LEAST 5 PACKETS FOR SERVER TO RECEIVE MESSAGE
    for (int i = 0; i < 5; ++i) {    
        client.SendPackets();
        transport.WritePackets();
        transport.ReadPackets();
        client.ReceivePackets();
        client.CheckForTimeOut();

        time += deltaTime;
        client.AdvanceTime(time);
        transport.AdvanceTime(time); 

        if (client.IsDisconnected())
            break;

        platform_sleep(deltaTime);
    }

    // Disconnect
    client.Disconnect();
    for (int i = 0; i < 1000; ++i) {
        client.SendPackets();
        transport.WritePackets();
        transport.ReadPackets();
        client.ReceivePackets();
        client.CheckForTimeOut();

        time += deltaTime;
        client.AdvanceTime(time);
        transport.AdvanceTime(time); 

        if (client.IsDisconnected()) {
            break;
        }
        platform_sleep(deltaTime);
    }
    return 0;
}

int main()
{
    if (!InitializeYojimbo()) {
        printf( "error: failed to initialize Yojimbo!\n" );
        return 1;
    }
    int result = ClientMain();
    ShutdownYojimbo();
    return result;
}
```

Server
```
#define SERVER 1
#define LOGGING 1

#include "shared.h"
#include <signal.h>

static volatile int quit = 0;

void interrupt_handler(int)
{
    quit = 1;
}

int ServerMain()
{
    double time = 0.0;
    const double deltaTime = 0.1;

    signal(SIGINT, interrupt_handler);

    // Setup transport
    Address bindAddress("0.0.0.0", ServerPort);
    Address publicAddress("127.0.0.1", ServerPort);
    NetworkTransport transport(GetDefaultAllocator(), bindAddress, 
        ProtocolId, time);
    if (transport.GetError() != SOCKET_ERROR_NONE) {
        return 1;
    }
    transport.SetFlags(TRANSPORT_FLAG_INSECURE_MODE);

    // Configure connection properties 
    ClientServerConfig config;
    config.connectionConfig.maxPacketSize = 1500;
    config.connectionConfig.numChannels = 1;
    config.connectionConfig.channel[0].type = CHANNEL_TYPE_UNRELIABLE_UNORDERED;
    
    // Start server
    GameServer server(GetDefaultAllocator(), transport, config, time);
    server.SetServerAddress(publicAddress);
    server.SetFlags(SERVER_FLAG_ALLOW_INSECURE_CONNECT);
    server.Start();

    // Receive and process messages
    int numMessagesReceived = 0;
    while (!quit) {
        server.SendPackets();
        transport.WritePackets();
        transport.ReadPackets();
        server.ReceivePackets();
        server.CheckForTimeOut();

        time += deltaTime;
        server.AdvanceTime(time);
        transport.AdvanceTime(time);

        for (int j = 0; j < server.GetMaxClients(); ++j) {
            if (server.IsClientConnected(j)) {
                while (true) {
                    Message *message = server.ReceiveMsg(j);
                    if (!message) {
                        break;
                    }
                    ++numMessagesReceived;
                    server.ReleaseMsg(j, message);
                }
            }
        }
        platform_sleep(deltaTime);
    }

    printf("numMessagesReceived = %d\n", numMessagesReceived); 
    server.Stop();
    return 0;
}

int main()
{
    if (!InitializeYojimbo()) {
        return 1;
    }
    int result = ServerMain();
    ShutdownYojimbo();
    return result; 
}
```

In that sample code, after the client calls `SendMsg()`, at least 5 `SendPackets()+WritePackets()+...` iterations must be called before the server is able to receive the message. Is that to be expected?

The strange thing is that the 5 "pumps" required in the sample code is still dramatically less than my actual code (5 vs 300). So there's obviously something going on in my actual code that I'll need to track down.

I'm just trying to understand what the proper behavior of `SendMsg()` in relation to a `SendPackets()` should be; essentially, will the message enqueued by `SendMsg()` be went in the next "pump" or will it take a few "pumps" for the message to be sent. If the latter is the case, does that mean that a client messaged enqueued with `SendMessage()` at time `t0` won't actually be received by the server until time `t0 + num_pumps * deltaTime`?

**Comment by gafferongames** [comment]
Thanks. I'll take a look at this tonight.

**Comment by mikesun** [comment]
Argh, I'm sorry, I figured out the issue at it was a stupid mistake on my part. I had different `deltaTimes` on the server and client by accident (`0.1` vs `0.02`). Sorry about that :(
