### ISSUE TITLE
Raspberry Pi build support?

### ISSUE THREAD

**Issue by thegabman** [networkprotocol/libyojimbo#38]
Hi,
I tried to compile yojimbo on pi 3 for some udp communication. I managed to build premake5, sodium and mbedtls. After the execution of premake on yojimbo i tried to use make to build it but it said that there are 2 unknown flags. -m64 and -msse2. Sure, thats because of the arm architecture. I removed these flags and yojimbo compiled. But linking against the resulting libyojimbo.a file results in a linker error on calling the initialize function of yojimbo. 
Would be incredible if there are plans to support raspberry pi!

Thank you very much!

**Comment by gafferongames** [comment]
What is the linker error? What steps do I have to take to build for Raspberry Pi?

**Comment by gafferongames** [comment]
Oh if it's just a linker error on the initialize, um. That would mean you are not linking to the yojimbo library properly? That's just a function, there should be nothing complex there.

**Comment by underscorediscovery** [comment]
Did you replace m64 with an arm architecture of what you're linking to? It might be defaulting to say, armv6 and your binary is armv7 so it's not seeing the right architecture. Make sure you're setting the same linker flags for the lib and what you're linking it to, and try using verbose flags to see if it expands on why.

**Comment by thegabman** [comment]
Hi,
Sorry. It was just a fault of mine.
To make it work I just had to change the platform from x64 to ARM and remove the enablesse flag in the premake script. Removing the compilerflags in the makefile like I did before was incorrect. 
Everyhing works fine now. 

Thank you very much!
