### ISSUE TITLE
Build failed when link with libsodium on macOS

### ISSUE THREAD

**Issue by linuxaged** [networkprotocol/libyojimbo#41]
make all
    ==== Building yojimbo (debug_x64) ====
    ==== Building test (debug_x64) ====
    Linking test
    ld: library not found for -lsodium
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [bin/test] Error 1
    make: *** [test] Error 2

macOS 10.12.3

Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix

homebrew config
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 146a4bf1580b0cc2ea22b6df6320fab43f3f3e76
Core tap last commit: 23 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/apple/.rvm/rubies/ruby-1.9.3-p194/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: N/A
X11: 2.7.7 => /opt/X11

    brew ls libsodium
    /usr/local/Cellar/libsodium/1.0.12/include/sodium/ (57 files)
    /usr/local/Cellar/libsodium/1.0.12/include/sodium.h
    /usr/local/Cellar/libsodium/1.0.12/lib/libsodium.18.dylib
    /usr/local/Cellar/libsodium/1.0.12/lib/pkgconfig/libsodium.pc
    /usr/local/Cellar/libsodium/1.0.12/lib/ (2 other files)

**Comment by gafferongames** [comment]
Is anybody else getting this issue? Working fine over here.

**Comment by mikesun** [comment]
I haven't had any issues on Mac.

**Comment by Vavius** [comment]
No issues. El Capitan 10.11.6. 
I've seen linker errors like that after switching Xcode versions. Try `xcode-select --install`

**Comment by gafferongames** [comment]
I'm on Sierra over here and trying to upgrade brew to latest to see if that breaks anything.

**Comment by gafferongames** [comment]
Compiles and links fine over here. Seconded, try: xcode-select --install

**Comment by gafferongames** [comment]
gafferongames:libyojimbo gaffer$ brew --version
Homebrew 1.1.11
Homebrew/homebrew-core (git revision bfe7e; last commit 2017-03-27)

**Comment by gafferongames** [comment]
gafferongames:libyojimbo gaffer$ brew ls libsodium
/usr/local/Cellar/libsodium/1.0.12/include/sodium/ (57 files)
/usr/local/Cellar/libsodium/1.0.12/include/sodium.h
/usr/local/Cellar/libsodium/1.0.12/lib/libsodium.18.dylib
/usr/local/Cellar/libsodium/1.0.12/lib/pkgconfig/libsodium.pc
/usr/local/Cellar/libsodium/1.0.12/lib/ (2 other files)

**Comment by gafferongames** [comment]
gafferongames:libyojimbo gaffer$ brew --config
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bfe7eefdf2c591c56742b6d07aa09fe2bf53746f
Core tap last commit: 60 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_111
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.6 => /opt/X11

**Comment by gafferongames** [comment]
gafferongames:libyojimbo gaffer$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by linuxaged** [comment]
i'm not on Mac currently, will try `xcode-select --install` after going home.

Any other suggestion?

**Comment by gafferongames** [comment]
Did `xcode-select --install' sort it out for you?

**Comment by linuxaged** [comment]
Yes, thanks!
Sorry for the late reply.

    ➜  libyojimbo git:(968fa62) make all                                             
    ==== Building yojimbo (debug_x64) ====
    ==== Building test (debug_x64) ====
    Linking test
    ==== Building info (debug_x64) ====
    Creating obj/x64/Debug/info
    info.cpp
    Linking info
    ==== Building client (debug_x64) ====
    Creating obj/x64/Debug/client
    client.cpp
    Linking client
    ==== Building server (debug_x64) ====
    Creating obj/x64/Debug/server
    server.cpp
    Linking server
    ==== Building secure_client (debug_x64) ====
    Creating obj/x64/Debug/secure_client
    secure_client.cpp
    Linking secure_client
    ==== Building secure_server (debug_x64) ====
    Creating obj/x64/Debug/secure_server
    secure_server.cpp
    Linking secure_server
    ==== Building client_server (debug_x64) ====
    Creating obj/x64/Debug/client_server
    client_server.cpp
    Linking client_server
    ==== Building soak (debug_x64) ====
    Creating obj/x64/Debug/soak
    soak.cpp
    Linking soak
    ==== Building profile (debug_x64) ====
    Creating obj/x64/Debug/profile
    profile.cpp
    Linking profile

**Comment by gafferongames** [comment]
Excellent! Closing out
