### ISSUE TITLE
Possible error in matcher, return instead of goto.

### ISSUE THREAD

**Issue by tbelaire** [networkprotocol/libyojimbo#6]
I'm curious as to why you have a `return` here, where all the other branches have a `goto cleanup;`

https://github.com/networkprotocol/libyojimbo/blob/master/yojimbo_matcher.cpp#L128
```
        if ( ( ret = mbedtls_ssl_config_defaults( &m_internal->conf,
                        MBEDTLS_SSL_IS_CLIENT,
                        MBEDTLS_SSL_TRANSPORT_STREAM,
                        MBEDTLS_SSL_PRESET_DEFAULT ) ) != 0 )
        {
            m_status = MATCHER_FAILED;
            return; // <-- All the other error branches are `goto cleanup;`
        }
    // ....
cleanup:
      mbedtls_ssl_close_notify( &m_internal->ssl );
```

I don't actually know enough about how the different mbedtls functions work to say this is a bug, but it looks suspicious to have only one error path return directly.

**Comment by gafferongames** [comment]
Thanks for reporting this! I'll take a look. -- cheers

**Comment by gafferongames** [comment]
Yepppp. That's a bug. Fixing now

**Comment by gafferongames** [comment]
Fixed.

**Comment by gafferongames** [comment]
ps. This matcher code is pretty naff, it's derived from sample code and I haven't spent a lot of time cleaning it up. I'm going to need to make the matcher operations non-blocking on the calling thread at same point, and I figured I would clean it up properly then. -- cheers
