### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [networkprotocol/libyojimbo#7]
Would you like to [replace any double quotes](https://github.com/networkprotocol/libyojimbo/blob/18bdacf46bc6a15045e24d7c1ceb0fea87d2b4b1/yojimbo.h#L28 "Check header file inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by gafferongames** [comment]
Can you explain why this is important? Is it so libyojimbo can be installed to /usr/local/include/libyojimbo or equivalent? Do I only need to do this for files inside yojimbo.h, or all includes inside yojimbo source?

Thanks

**Comment by gafferongames** [comment]
To be clear, I am most likely going to make this change. Just let me know your use case, why it's important and I'll make it happen. Is it breaking you in some way or blocking your work using yojimbo?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by gafferongames** [comment]
Hmmm. It doesn't seem like you have an actual use case. Closing

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

**Comment by gafferongames** [comment]
This seems incredibly academic.
