### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [networkprotocol/libyojimbo#8]
[Extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in [the destructor for the class "ServerData"](https://github.com/networkprotocol/libyojimbo/blob/01033eb0da3d6af1e05e716570917218a9122129/tests/profile.cpp#L60 "Update candidate: ServerData destructor").

**Comment by gafferongames** [comment]
I appreciate that it is not necessary to check the pointer before calling delete, but I don't think this is worth fixing. The profile.cpp is quickly hacked up sample code for profiling the library and not part of the library or production code. -- cheers
